---
name: weather_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^0.13.4
  geolocator: ^10.0.1
  geocode: ^1.0.3
  bloc: ^8.1.2
  google_places_flutter: ^2.0.6
  country_state_city: ^0.1.6
  sqflite: ^2.3.0
  path: ^1.8.3
  table_calendar: ^3.0.9
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/weather_app_logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
