name: my_weather_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  envied: ^1.0.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  

dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.0.1
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^5.1.0
