// Mocks generated by Mockito 5.4.5 from annotations
// in my_weather_api/test/src/weather_api/repositories/weather_api_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_weather_api/src/weather_api/datasources/remote_data_sources/weather_api.dart'
    as _i4;
import 'package:my_weather_api/src/weather_api/models/location_weather_data.dart'
    as _i3;
import 'package:my_weather_api/src/weather_api/models/weather_data.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherData_0 extends _i1.SmartFake implements _i2.WeatherData {
  _FakeWeatherData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationWeatherData_1 extends _i1.SmartFake
    implements _i3.LocationWeatherData {
  _FakeLocationWeatherData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherApi extends _i1.Mock implements _i4.WeatherApi {
  @override
  _i5.Future<_i2.WeatherData> getWeatherData({
    required double? lat,
    required double? long,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [],
          {
            #lat: lat,
            #long: long,
          },
        ),
        returnValue: _i5.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getWeatherData,
            [],
            {
              #lat: lat,
              #long: long,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getWeatherData,
            [],
            {
              #lat: lat,
              #long: long,
            },
          ),
        )),
      ) as _i5.Future<_i2.WeatherData>);

  @override
  _i5.Future<_i3.LocationWeatherData> getLocationWeatherData(
          {required String? locationName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationWeatherData,
          [],
          {#locationName: locationName},
        ),
        returnValue: _i5.Future<_i3.LocationWeatherData>.value(
            _FakeLocationWeatherData_1(
          this,
          Invocation.method(
            #getLocationWeatherData,
            [],
            {#locationName: locationName},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.LocationWeatherData>.value(
            _FakeLocationWeatherData_1(
          this,
          Invocation.method(
            #getLocationWeatherData,
            [],
            {#locationName: locationName},
          ),
        )),
      ) as _i5.Future<_i3.LocationWeatherData>);
}
